### ISSUE TITLE
there is something missing

### ISSUE THREAD

**Issue by sinsa110** [muatik/naive-bayes-classifier#4]
the code `newsTrainer = Trainer(tokenizer.Tokenizer(stop_words=[], signs_to_remove=["?!#%&"])` has missed a `)` at last, the same to `newsClassifier = Classifier(newsTrainer.data, tokenizer.Tokenizer(stop_words=[], signs_to_remove=["?!#%&"])`

**Comment by gerardtoko** [comment]
Exactly
